### PR TITLE
Add detrazioni and fix threshold tax calculation

### LINKED ISSUE #11: Add detrazioni and bonus IRPEF
2022: 1880 | 1910+1190*(28k-r)/(28k-15k) | 1910*(50k-r)/(50k-28k) ([ref](https://www.fiscoetasse.com/approfondimenti/14503-detrazioni-irpef-cosa-cambia-con-la-legge-di-bilancio-2022.html))

### PR DESCRIPTION
**Pull request by andybergon**
@cpaoli 

Closes #11

### CODE REVIEW

File: calculator.js [hunk 1]
```diff
@@ -531,24 +532,42 @@ function calcolaIrpefRegione(imponibile, regione) {
...
     let tasseTotale = 0;
     let resto = lordo;
-    const sogliaPrecedente = 0;
+    let sogliaPrecedente = 0;
+
     for (const soglia in soglieToPercentualeMarginale) {
         const percentuale = soglieToPercentualeMarginale[soglia]
         const deltaSoglia = soglia - sogliaPrecedente;
         const used = Math.min(deltaSoglia, resto);
+        sogliaPrecedente = soglia
```
Comment (andybergon) [inline calculator.js:570]: ^ this was the threshold tax calculation bug
